config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  post '/' => 'home#create_subscription', as: :create_subscription
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  has_many :subscriptions
  validates :subject, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :newsletter
  validates :name, presence: true
  validates :email, presence: true
  validates :newsletter, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @subscription = Subscription.new``
  end

  def create_subscription
    @subscription = Subscription.new(subscription_params)

    if @subscription.save
      flash[:notice] = "Subscription confirmed!"
      redirect_to root_path
    else
      flash[:error] = "Subscription failed."
      render :index
    end
  end

  private
  def subscription_params
    params.require(:subscription).permit(:name, :email, :newsletter_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert alert-success"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-danger"
    when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_errors_list(resource, field)
    if has_validation_error?(resource, field)
      content_tag :div, class: 'invalid-feedback d-block' do
        content_tag :ul, class: 'list-unstyled' do
          resource&.errors[field.to_sym].each {|error|
            concat content_tag(:li, error)
          }
        end
      end
    end
  end

  def bootstrap_error_class(resource, field)
    has_validation_error?(resource, field) ? 'is-invalid' : ''
  end

  def has_validation_error?(resource, field)
    resource&.errors[field.to_sym].present?
  end
end

app/views/home/index.html.erb
<%= form_for(@subscription, as: :subscription, url: create_subscription_path) do |f| %>
  
  <div class="form-group">
    <%= f.label :newsletter %>
    <%= f.select :newsletter_id, options_from_collection_for_select(Newsletter.all, :id, :subject), {},
                 { class: "form-control #{bootstrap_error_class(@subscription, :newsletter)}"} %>
    <%= bootstrap_errors_list(@subscription, :newsletter) %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autocomplete: "name", class: "form-control #{bootstrap_error_class(@subscription, :name)}" %>
    <%= bootstrap_errors_list(@subscription, :name) %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, autocomplete: "email", class: "form-control #{bootstrap_error_class(@subscription, :email)}" %>
    <%= bootstrap_errors_list(@subscription, :email) %>
  </div>

  <div class="form-group">
    <%= button_tag data: {disable_with: "Wait..."}, class: "btn btn-primary btn-lg btn-block", tabindex: "3" do %>
      Register
    <% end %>
  </div>

<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_topbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a href="#" class="navbar-brand">Newsletter</a>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CdRailsRspecCapybara</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/topbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>